/*
 * MagicTelecomAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/24/2016
 */
using System;

namespace MagicTelecomAPI.PCL
{
    public partial class Configuration
    {
        //The base Uri for API calls
        public static string BaseUri = "https://api.magictelecom.com/app_dev.php";

        //API Token
        //TODO: Replace the XAuthToken with an appropriate value
        public static string XAuthToken = "123abcqwerty";

    }
}