/*
 * MagicTelecomAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/24/2016
 */
using System;
using MagicTelecomAPI.PCL.Controllers;
using MagicTelecomAPI.PCL.Http.Client;

namespace MagicTelecomAPI.PCL
{
    public partial class MagicTelecomAPIClient
    {

        /// <summary>
        /// Singleton access to Users controller
        /// </summary>
        public UsersController Users
        {
            get
            {
                return UsersController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Accounts controller
        /// </summary>
        public AccountsController Accounts
        {
            get
            {
                return AccountsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Dids controller
        /// </summary>
        public DidsController Dids
        {
            get
            {
                return DidsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to DidsProducts controller
        /// </summary>
        public DidsProductsController DidsProducts
        {
            get
            {
                return DidsProductsController.Instance;
            }
        }

        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        
        /// <summary>
        /// Default constructor
        /// </summary>
        public MagicTelecomAPIClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public MagicTelecomAPIClient(string xAuthToken = "123abcqwerty")
        {
            Configuration.XAuthToken = xAuthToken;
        }
    }
}