/*
 * MagicTelecomAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/24/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using MagicTelecomAPI.PCL;

namespace MagicTelecomAPI.PCL.Models
{
    public class DidItem : Item 
    {
        // These fields hold the values for the public properties.
        private string phoneNumber;
        private int trunkId;
        private string didTypeHandle;
        private CallerLocation callerLocation;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("phone_number")]
        public string PhoneNumber 
        { 
            get 
            {
                return this.phoneNumber; 
            } 
            set 
            {
                this.phoneNumber = value;
                onPropertyChanged("PhoneNumber");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("trunk_id")]
        public int TrunkId 
        { 
            get 
            {
                return this.trunkId; 
            } 
            set 
            {
                this.trunkId = value;
                onPropertyChanged("TrunkId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("did_type_handle")]
        public string DidTypeHandle 
        { 
            get 
            {
                return this.didTypeHandle; 
            } 
            set 
            {
                this.didTypeHandle = value;
                onPropertyChanged("DidTypeHandle");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("_caller_location")]
        public CallerLocation CallerLocation 
        { 
            get 
            {
                return this.callerLocation; 
            } 
            set 
            {
                this.callerLocation = value;
                onPropertyChanged("CallerLocation");
            }
        }
    }
} 