/*
 * MagicTelecomAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/24/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using MagicTelecomAPI.PCL;

namespace MagicTelecomAPI.PCL.Models
{
    public class TrunkItem : Item 
    {
        // These fields hold the values for the public properties.
        private int channels;
        private string trunkHandle;
        private string sipUri;
        private string attributes;
        private Routing routing;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("channels")]
        public int Channels 
        { 
            get 
            {
                return this.channels; 
            } 
            set 
            {
                this.channels = value;
                onPropertyChanged("Channels");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("trunk_handle")]
        public string TrunkHandle 
        { 
            get 
            {
                return this.trunkHandle; 
            } 
            set 
            {
                this.trunkHandle = value;
                onPropertyChanged("TrunkHandle");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("sip_uri")]
        public string SipUri 
        { 
            get 
            {
                return this.sipUri; 
            } 
            set 
            {
                this.sipUri = value;
                onPropertyChanged("SipUri");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("attributes")]
        public string Attributes 
        { 
            get 
            {
                return this.attributes; 
            } 
            set 
            {
                this.attributes = value;
                onPropertyChanged("Attributes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("_routing")]
        public Routing Routing 
        { 
            get 
            {
                return this.routing; 
            } 
            set 
            {
                this.routing = value;
                onPropertyChanged("Routing");
            }
        }
    }
} 